version: '3'

services:
    production:
        container_name: next_cms
        volumes:
            - files_upload:/app/uploads
            - database_sqlite:/app/db
        restart: always

#   prisma:
#     image: prismagraphql/prisma:1.34
#     restart: always
#     ports:
#       - '4466:4466'
#     environment:
#       PRISMA_CONFIG: |
#         port: 4466
#         managementApiSecret: mysecret42
#         databases:
#           default:
#             connector: postgres
#             host: postgres-db
#             port: 5432
#             user: prisma
#             password: prisma

# postgres-db:
#     image: postgres:10.3
#     restart: always
#     environment:
#     POSTGRES_USER: prisma
#     POSTGRES_PASSWORD: prisma
#     volumes:
#     - postgres:/var/lib/postgresql/data

volumes:
    files_upload:
    database_sqlite:

networks:
    my_network:
        external: true
# version: '3'
# services:
#   prisma:
#     image: prismagraphql/prisma:1.34
#     restart: always
#     ports:
#       - '4466:4466'
#     environment:
#       PRISMA_CONFIG: |
#         port: 4466
#         managementApiSecret: mysecret42
#         databases:
#           default:
#             connector: postgres
#             host: postgres-db
#             port: 5432
#             user: prisma
#             password: prisma
#   postgres-db:
#     image: postgres:10.3
#     restart: always
#     environment:
#       POSTGRES_USER: prisma
#       POSTGRES_PASSWORD: prisma
#     volumes:
#       - postgres:/var/lib/postgresql/data
# volumes:
#   postgres: ~
