version: '3'

services:
    production:
        container_name: next_cms
        build:
            context: .
            dockerfile: Dockerfile
            # args:
            #     ENV_VARIABLE: ${ENV_VARIABLE}
            #     NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
        volumes:
            - files_upload:/app/uploads
            - database_sqlite:/app/db
        restart: always
        # networks:
        #     - my_network

volumes:
    files_upload:
    database_sqlite:
# networks:
#     my_network:
#         external: true

#
#
#

#   prisma:
#     image: prismagraphql/prisma:1.34
#     restart: always
#     ports:
#       - '4466:4466'
#     environment:
#       PRISMA_CONFIG: |
#         port: 4466
#         managementApiSecret: mysecret42
#         databases:
#           default:
#             connector: postgres
#             host: postgres-db
#             port: 5432
#             user: prisma
#             password: prisma

# postgres-db:
#     image: postgres:10.3
#     restart: always
#     environment:
#     POSTGRES_USER: prisma
#     POSTGRES_PASSWORD: prisma
#     volumes:
#     - postgres:/var/lib/postgresql/data
# version: '3'
# services:
#   prisma:
#     image: prismagraphql/prisma:1.34
#     restart: always
#     ports:
#       - '4466:4466'
#     environment:
#       PRISMA_CONFIG: |
#         port: 4466
#         managementApiSecret: mysecret42
#         databases:
#           default:
#             connector: postgres
#             host: postgres-db
#             port: 5432
#             user: prisma
#             password: prisma
#   postgres-db:
#     image: postgres:10.3
#     restart: always
#     environment:
#       POSTGRES_USER: prisma
#       POSTGRES_PASSWORD: prisma
#     volumes:
#       - postgres:/var/lib/postgresql/data
# volumes:
#   postgres: ~

# # Set the version of docker compose to use
# version: '3.9'

# # The containers that compose the project
# services:
#   db:
#     image: postgres:13
#     restart: always
#     container_name: integration-tests-prisma
#     ports:
#       - '5433:5432'
#     environment:
#       POSTGRES_USER: prisma
#       POSTGRES_PASSWORD: prisma
#       POSTGRES_DB: tests
