version: '3'

services:
    production:
        image: next-cms
        ports:
            - '${PORT}:${PORT}'
    frontend:
        image: node:lts
        volumes:
            - myuploads:/app/uploads
            - myuploads:/app/db

volumes:
    myuploads:
