import { CodeLanguage } from '@prisma/client'

type LanguagesType = { [key in CodeLanguage]: { name: string; code: string; en: string; flag?: string } }

const languages: LanguagesType = {
    AF: { name: 'Afrikaans', code: 'af', en: 'Afrikaans', flag: '🇿🇦' },
    SQ: { name: 'Shqiptare', code: 'sq', en: 'Albanian', flag: '🇦🇱' },
    AR: { name: 'عربي', code: 'ar', en: 'Arabic', flag: '🇸🇦' },
    EU: { name: 'Euskara', code: 'eu', en: 'Basque' },
    BE: { name: 'беларускі', code: 'be', en: 'Belarusian', flag: '🇧🇾' },
    BG: { name: 'български', code: 'bg', en: 'Bulgarian', flag: '🇧🇬' },
    CA: { name: 'Català', code: 'ca', en: 'Catalan' },
    ZH: { name: '中文', code: 'zh', en: 'Chinese', flag: '🇨🇳' },
    HR: { name: 'Hrvatski', code: 'hr', en: 'Croatian', flag: '' },
    CS: { name: 'Czech', code: 'cs', en: 'Čeština' },
    DA: { name: 'Danish', code: 'da', en: 'Dansk', flag: '🇩🇰' },
    NL: { name: 'Dutch', code: 'nl', en: 'Nederlands', flag: '🇳🇱' },
    EN: { name: 'English', code: 'en', en: 'English', flag: '🇬🇧' },
    ET: { name: 'Estonian', code: 'et', en: 'Eesti keel', flag: '🇪🇪' },
    FO: { name: 'Faeroese', code: 'fo', en: 'Faeroese', flag: '🇫🇴' },
    FA: { name: 'Farsi', code: 'fa', en: 'Farsi', flag: '🇦🇫' },
    FI: { name: 'Finnish', code: 'fi', en: 'Finnish', flag: '🇫🇮' },
    FR: { name: 'Français', code: 'fr', en: 'French', flag: '🇫🇷' },
    GD: { name: 'Gaelic', code: 'gd', en: 'Gaelic' },
    DE: { name: 'German', code: 'de', en: 'German', flag: '🇩🇪' },
    EL: { name: 'Greek', code: 'el', en: 'Greek', flag: '🇬🇷' },
    HE: { name: 'Hebrew', code: 'he', en: 'Hebrew', flag: '🇮🇱' },
    HI: { name: 'Hindi', code: 'hi', en: 'Hindi', flag: '🇮🇳' },
    HU: { name: 'Hungarian', code: 'hu', en: 'Hungarian', flag: '🇭🇺' },
    IS: { name: 'Icelandic', code: 'is', en: 'Icelandic', flag: '🇮🇸' },
    ID: { name: 'Indonesian', code: 'id', en: 'Indonesian', flag: '🇮🇩' },
    GA: { name: 'Irish', code: 'ga', en: 'Irish', flag: '🇮🇪' },
    IT: { name: 'Italian', code: 'it', en: 'Italian', flag: '🇮🇹' },
    JA: { name: 'Japanese', code: 'ja', en: 'Japanese', flag: '🇯🇵' },
    KO: { name: 'Korean', code: 'ko', en: 'Korean', flag: '🇰🇷' },
    KU: { name: 'کوردی', code: 'ku', en: 'Kurdish', flag: '🇸🇾' },
    LV: { name: 'Latvian', code: 'lv', en: 'Latvian', flag: '🇱🇻' },
    LT: { name: 'Lithuanian', code: 'lt', en: 'Lithuanian', flag: '🇱🇹' },
    MK: { name: 'Macedonian (FYROM)', code: 'mk', en: 'Macedonian (FYROM)', flag: '🇲🇰' },
    ML: { name: 'Malayalam', code: 'ml', en: 'Malayalam' },
    MS: { name: 'Malaysian', code: 'ms', en: 'Malaysian', flag: '🇲🇾' },
    MT: { name: 'Maltese', code: 'mt', en: 'Maltese', flag: '🇲🇹' },
    NO: { name: 'Norwegian', code: 'no', en: 'Norwegian', flag: '🇳🇴' },
    NB: { name: 'Norwegian (Bokmål)', code: 'nb', en: 'Norwegian (Bokmål)', flag: '🇳🇴' },
    NN: { name: 'Norwegian (Nynorsk)', code: 'nn', en: 'Norwegian (Nynorsk)', flag: '🇳🇴' },
    PL: { name: 'Polish', code: 'pl', en: 'Polish', flag: '🇵🇱' },
    PT: { name: 'Portuguese', code: 'pt', en: 'Portuguese', flag: '🇵🇹' },
    PA: { name: 'Punjabi', code: 'pa', en: 'Punjabi', flag: '🇵🇰' },
    RM: { name: 'Rhaeto-Romanic', code: 'rm', en: 'Rhaeto-Romanic', flag: '🇮🇹' },
    RO: { name: 'Romanian', code: 'ro', en: 'Romanian', flag: '🇷🇴' },
    RU: { name: 'Russian', code: 'ru', en: 'Russian', flag: '🇷🇺' },
    SR: { name: 'Serbian', code: 'sr', en: 'Serbian', flag: '🇷🇸' },
    SK: { name: 'Slovak', code: 'sk', en: 'Slovak', flag: '🇸🇰' },
    SL: { name: 'Slovenian', code: 'sl', en: 'Slovenian', flag: '🇸🇮' },
    SB: { name: 'Sorbian', code: 'sb', en: 'Sorbian', flag: '🇷🇸' },
    ES: { name: 'Spanish', code: 'es', en: 'Spanish', flag: '🇪🇸' },
    SV: { name: 'Swedish', code: 'sv', en: 'Swedish', flag: '🇸🇪' },
    TH: { name: 'Thai', code: 'th', en: 'Thai', flag: '🇹🇭' },
    TS: { name: 'Tsonga', code: 'ts', en: 'Tsonga', flag: '🇲🇿' },
    TN: { name: 'Tswana', code: 'tn', en: 'Tswana', flag: '🇧🇼' },
    TR: { name: 'Turkish', code: 'tr', en: 'Turkish', flag: '🇹🇷' },
    UA: { name: 'Ukrainian', code: 'ua', en: 'Ukrainian', flag: '🇺🇦' },
    UR: { name: 'Urdu', code: 'ur', en: 'Urdu', flag: '🇵🇰' },
    VE: { name: 'Venda', code: 've', en: 'Venda', flag: '🇿🇼' },
    VI: { name: 'Vietnamese', code: 'vi', en: 'Vietnamese', flag: '🇻🇳' },
    CY: { name: 'Welsh', code: 'cy', en: 'Welsh', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
    XH: { name: 'Xosa', code: 'xh', en: 'Xhosa', flag: '🇿🇼' },
    JI: { name: 'Yiddish', code: 'ji', en: 'Yiddish', flag: '🇮🇱' },
    ZU: { name: 'Zulu', code: 'zu', en: 'Zulu', flag: '🇿🇦' },
}

export default languages
