const languages = {
    AF: { label: 'Afrikaans', code: 'af' },
    SQ: { label: 'Albanian', code: 'sq' },
    AR: { label: 'Arabic', code: 'ar-dz' },
    EU: { label: 'Basque', code: 'eu' },
    BE: { label: 'Belarusian', code: 'be' },
    BG: { label: 'Bulgarian', code: 'bg' },
    CA: { label: 'Catalan', code: 'ca' },
    ZH: { label: 'Chinese', code: 'zh' },
    HR: { label: 'Croatian', code: 'hr' },
    CS: { label: 'Czech', code: 'cs' },
    DA: { label: 'Danish', code: 'da' },
    NL: { label: 'Dutch', code: 'nl' },
    EN: { label: 'English', code: 'en' },
    ET: { label: 'Estonian', code: 'et' },
    FO: { label: 'Faeroese', code: 'fo' },
    FA: { label: 'Farsi', code: 'fa' },
    FI: { label: 'Finnish', code: 'fi' },
    FR: { label: 'French', code: 'fr' },
    GD: { label: 'Gaelic', code: 'gd' },
    DE: { label: 'German', code: 'de' },
    EL: { label: 'Greek', code: 'el' },
    HE: { label: 'Hebrew', code: 'he' },
    HI: { label: 'Hindi', code: 'hi' },
    HU: { label: 'Hungarian', code: 'hu' },
    IS: { label: 'Icelandic', code: 'is' },
    ID: { label: 'Indonesian', code: 'id' },
    GA: { label: 'Irish', code: 'ga' },
    IT: { label: 'Italian', code: 'it' },
    JA: { label: 'Japanese', code: 'ja' },
    KO: { label: 'Korean', code: 'ko' },
    KU: { label: 'Kurdish', code: 'ku' },
    LV: { label: 'Latvian', code: 'lv' },
    LT: { label: 'Lithuanian', code: 'lt' },
    MK: { label: 'Macedonian (FYROM)', code: 'mk' },
    ML: { label: 'Malayalam', code: 'ml' },
    MS: { label: 'Malaysian', code: 'ms' },
    MT: { label: 'Maltese', code: 'mt' },
    NO: { label: 'Norwegian', code: 'no' },
    NB: { label: 'Norwegian (Bokmål)', code: 'nb' },
    NN: { label: 'Norwegian (Nynorsk)', code: 'nn' },
    PL: { label: 'Polish', code: 'pl' },
    PT: { label: 'Portuguese', code: 'pt' },
    PA: { label: 'Punjabi', code: 'pa' },
    RM: { label: 'Rhaeto-Romanic', code: 'rm' },
    RO: { label: 'Romanian', code: 'ro' },
    RU: { label: 'Russian', code: 'ru' },
    SR: { label: 'Serbian', code: 'sr' },
    SK: { label: 'Slovak', code: 'sk' },
    SL: { label: 'Slovenian', code: 'sl' },
    SB: { label: 'Sorbian', code: 'sb' },
    ES: { label: 'Spanish', code: 'es' },
    SV: { label: 'Swedish', code: 'sv' },
    TH: { label: 'Thai', code: 'th' },
    TS: { label: 'Tsonga', code: 'ts' },
    TN: { label: 'Tswana', code: 'tn' },
    TR: { label: 'Turkish', code: 'tr' },
    UA: { label: 'Ukrainian', code: 'ua' },
    UR: { label: 'Urdu', code: 'ur' },
    VE: { label: 'Venda', code: 've' },
    VI: { label: 'Vietnamese', code: 'vi' },
    CY: { label: 'Welsh', code: 'cy' },
    XH: { label: 'Xhosa', code: 'xh' },
    JI: { label: 'Yiddish', code: 'ji' },
    ZU: { label: 'Zulu', code: 'zu' },
}

export default languages
