/*
  Warnings:

  - The values [VIEW_PAGE,UPDATE_PAGE,VIEW_CONTAINER,UPDATE_CONTAINER,VIEW_CONTENT,UPDATE_CONTENT,VIEW_MEDIA,VIEW_FORM,UPDATE_FORM] on the enum `RightType` will be removed. If these variants are still used in the database, this will fail.
  - You are about to drop the column `superUser` on the `Role` table. All the data in the column will be lost.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "RightType_new" AS ENUM ('VIEW_ALL_PAGE', 'VIEW_MY_PAGE', 'CREATE_PAGE', 'UPDATE_ALL_PAGE', 'UPDATE_MY_PAGE', 'DELETE_PAGE', 'UPDATE_PAGE_SECTION', 'VIEW_ALL_CONTAINER', 'VIEW_MY_CONTAINER', 'CREATE_CONTAINER', 'UPDATE_ALL_CONTAINER', 'UPDATE_MY_CONTAINER', 'DELETE_CONTAINER', 'UPDATE_CONTAINER_SECTION', 'UPDATE_CONTAINER_TEMPLATE_SECTION', 'VIEW_ALL_CONTENT', 'VIEW_MY_CONTENT', 'CREATE_CONTENT', 'UPDATE_ALL_CONTENT', 'UPDATE_MY_CONTENT', 'DELETE_CONTENT', 'UPDATE_CONTENT_SECTION', 'VIEW_ALL_MEDIA', 'VIEW_MY_MEDIA', 'UPLOAD_MEDIA', 'UPDATE_MEDIA', 'DELETE_MEDIA', 'VIEW_ALL_FORM', 'VIEW_MY_FORM', 'CREATE_FORM', 'UPDATE_ALL_FORM', 'UPDATE_MY_FORM', 'DELETE_FORM', 'VIEW_MESSAGE', 'READ_MESSAGE', 'DELETE_MESSAGE', 'VIEW_USER', 'CREATE_USER', 'UPDATE_USER', 'DELETE_USER', 'VIEW_ROLE', 'CREATE_ROLE', 'UPDATE_ROLE', 'DELETE_ROLE', 'VIEW_LAYOUT', 'UPDATE_LAYOUT', 'VIEW_SETTING', 'UPDATE_GENERAL', 'UPDATE_THEME', 'UPDATE_SMTP', 'REVALIDATE');
ALTER TABLE "Role" ALTER COLUMN "rights" TYPE "RightType_new"[] USING ("rights"::text::"RightType_new"[]);
ALTER TYPE "RightType" RENAME TO "RightType_old";
ALTER TYPE "RightType_new" RENAME TO "RightType";
DROP TYPE "RightType_old";
COMMIT;

-- DropForeignKey
ALTER TABLE "Login" DROP CONSTRAINT "Login_roleId_fkey";

-- AlterTable
ALTER TABLE "Container" ADD COLUMN     "createdByUserId" INTEGER;

-- AlterTable
ALTER TABLE "Content" ADD COLUMN     "createdByUserId" INTEGER;

-- AlterTable
ALTER TABLE "Login" ADD COLUMN     "root" BOOLEAN NOT NULL DEFAULT false,
ALTER COLUMN "roleId" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Page" ADD COLUMN     "createdByUserId" INTEGER;

-- AlterTable
ALTER TABLE "Role" DROP COLUMN "superUser";

-- AddForeignKey
ALTER TABLE "Login" ADD CONSTRAINT "Login_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "Role"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Page" ADD CONSTRAINT "Page_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Container" ADD CONSTRAINT "Container_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Content" ADD CONSTRAINT "Content_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
