/*
  Warnings:

  - The values [UPDATE_MEDIA,DELETE_MEDIA] on the enum `RightType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "RightType_new" AS ENUM ('VIEW_ALL_PAGE', 'VIEW_MY_PAGE', 'CREATE_PAGE', 'UPDATE_ALL_PAGE', 'UPDATE_MY_PAGE', 'DELETE_ALL_PAGE', 'DELETE_MY_PAGE', 'UPDATE_ALL_PAGE_SECTION', 'UPDATE_MY_PAGE_SECTION', 'VIEW_ALL_CONTAINER', 'VIEW_MY_CONTAINER', 'CREATE_CONTAINER', 'UPDATE_ALL_CONTAINER', 'UPDATE_MY_CONTAINER', 'DELETE_ALL_CONTAINER', 'DELETE_MY_CONTAINER', 'UPDATE_ALL_CONTAINER_SECTION', 'UPDATE_MY_CONTAINER_SECTION', 'UPDATE_ALL_CONTAINER_TEMPLATE_SECTION', 'UPDATE_MY_CONTAINER_TEMPLATE_SECTION', 'VIEW_ALL_CONTENT', 'VIEW_MY_CONTENT', 'CREATE_CONTENT', 'UPDATE_ALL_CONTENT', 'UPDATE_MY_CONTENT', 'DELETE_ALL_CONTENT', 'DELETE_MY_CONTENT', 'UPDATE_ALL_CONTENT_SECTION', 'UPDATE_MY_CONTENT_SECTION', 'VIEW_ALL_MEDIA', 'VIEW_MY_MEDIA', 'UPLOAD_MEDIA', 'UPDATE_ALL_MEDIA', 'UPDATE_MY_MEDIA', 'DELETE_ALL_MEDIA', 'DELETE_MY_MEDIA', 'VIEW_ALL_FORM', 'VIEW_MY_FORM', 'CREATE_FORM', 'UPDATE_ALL_FORM', 'UPDATE_MY_FORM', 'DELETE_FORM', 'VIEW_MESSAGE', 'READ_MESSAGE', 'DELETE_MESSAGE', 'VIEW_USER', 'CREATE_USER', 'UPDATE_USER', 'DELETE_USER', 'VIEW_ROLE', 'CREATE_ROLE', 'UPDATE_ROLE', 'DELETE_ROLE', 'VIEW_LAYOUT', 'UPDATE_LAYOUT', 'VIEW_SETTING', 'UPDATE_GENERAL', 'UPDATE_THEME', 'UPDATE_SMTP', 'REVALIDATE');
ALTER TABLE "Role" ALTER COLUMN "rights" TYPE "RightType_new"[] USING ("rights"::text::"RightType_new"[]);
ALTER TYPE "RightType" RENAME TO "RightType_old";
ALTER TYPE "RightType_new" RENAME TO "RightType";
DROP TYPE "RightType_old";
COMMIT;
