import type { GetStaticPathsContext } from 'next'
import Head from 'next/head'
import { Prisma } from '@prisma/client'
import type { Page } from '@prisma/client'
// import Link from 'next/link'
import get from 'lodash.get'
import { prisma } from '../utils/prisma'

const NotFound = ({ title }: Prisma.PageCreateInput) => {
    return (
        <div>
            <Head>
                <title>{title}</title>
                {/* <meta
                    name="description"
                    content="Generated by create next app"
                /> */}
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header></header>

            <main>{title}</main>

            <footer></footer>
        </div>
    )
}

export async function getStaticProps(context: GetStaticPathsContext) {
    const allHomepages = await prisma.page.findMany({
        where: { type: 'error' },
    })

    const page: Page = get(allHomepages, '0', {})

    const revalidate = await prisma.setting.findUnique({
        where: { name: 'revalidate' },
    })

    return {
        props: {
            ...page,
            updatedAt: Math.floor(
                (page?.updatedAt?.getMilliseconds() || 1) / 1000
            ),
        },
        revalidate: revalidate ? parseInt(revalidate.value) : 60,
    }
}

export default NotFound
