import type { GetStaticPathsContext } from 'next'
import Head from 'next/head'
import { PrismaClient, Prisma } from '@prisma/client'
import type { Page } from '@prisma/client'
// import Link from 'next/link'
import get from 'lodash.get'

const prisma = new PrismaClient()

const Home = ({ title }: Prisma.PageCreateInput) => {
    return (
        <div>
            <Head>
                <title>{title}</title>
                {/* <meta
                    name="description"
                    content="Generated by create next app"
                /> */}
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header></header>

            <main>{title}</main>

            <footer></footer>
        </div>
    )
}

export async function getStaticProps(context: GetStaticPathsContext) {
    const allHomepages = await prisma.page.findMany({
        where: { type: 'home' },
    })

    const page: Page = get(allHomepages, '0', {})

    return {
        props: {
            ...page,
            updatedAt: Math.floor(
                (page?.updatedAt?.getMilliseconds() || 1) / 1000
            ),
        },
        revalidate: 60,
    }
}

export default Home
