import { useState, useEffect } from 'react'
import { Divider, Steps } from 'antd'
import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'

const Install: NextPage = () => {
    useEffect(() => {}, [])

    return (
        <div>
            <Head>
                <title>Install</title>
                {/* <meta
            name="description"
            content="Generated by create next app"
        /> */}
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header></header>

            <main>
                <Link href="/">
                    <a>Back home</a>
                </Link>
            </main>

            <footer></footer>
        </div>
    )
}

export default Install
