// import { Divider, Steps } from 'antd'
import { Button, Result, Spin } from 'antd'
import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
// import Image from 'next/image'
import { initPages } from '../network/api'
import { useQuery, UseQueryResult } from 'react-query'
import { prisma } from '../utils/prisma'

const Install: NextPage = () => {
    const install: UseQueryResult<void, Error> = useQuery<void, Error>(['install'], () => initPages(), {
        refetchOnMount: false,
        refetchOnReconnect: false,
    })

    return (
        <div>
            <Head>
                <title>Install</title>
                {/* <meta
            name="description"
            content="Generated by create next app"
        /> */}
            </Head>

            <main>
                <div
                    style={{
                        backgroundColor: '#f0f2f5',
                        height: '100vh',
                        width: '100vw',
                        display: 'flex',
                        justifyContent: 'center',
                        alignItems: 'center',
                    }}
                >
                    {install.isLoading ? (
                        <Spin tip="Installing..." />
                    ) : (
                        <Result
                            status={install.status === 'error' ? 'error' : 'success'}
                            title={
                                install.status === 'error'
                                    ? 'Installation failed, please try again'
                                    : 'Installation completed successfully'
                            }
                            extra={[
                                install.status === 'error' ? (
                                    <Button onClick={() => install.refetch} type="primary">
                                        Retry
                                    </Button>
                                ) : (
                                    <Link href="/" key="home">
                                        <a>
                                            <Button type="primary">Back home</Button>
                                        </a>
                                    </Link>
                                ),
                            ]}
                        />
                    )}
                </div>
            </main>
        </div>
    )
}

export async function getStaticProps() {
    const revalidate = await prisma.setting.findUnique({
        where: { name: 'installed' },
    })

    return {
        props: {},
        notFound: revalidate?.value === 'true',
    }
}

export default Install
